spring:
  application:
    name: assignment

  datasource:
    url: jdbc:mysql://localhost:3306/assignment
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  batch:
    jdbc:
      initialize-schema: always

logging:
level:
    org.springframework: INFO
    org.hibernate: INFO
    org.springframework.jdbc.core.JdbcTemplate: DEBUG