CREATE DATABASE IF NOT EXISTS assignment;
USE assignment;
CREATE TABLE store_info (
    store_code VARCHAR(40) PRIMARY KEY COMMENT "상가업소번호",
    store_name VARCHAR(255) NOT NULL COMMENT "상호명",
    branch_name VARCHAR(255) COMMENT "지점명",
    large_category_code VARCHAR(10) COMMENT "상권업종대분류코드",
    large_category_name VARCHAR(50) COMMENT "상권업종대분류명",
    medium_category_code VARCHAR(10) COMMENT "상권업종중분류코드",
    medium_category_name VARCHAR(50) COMMENT "상권업종중분류명",
    small_category_code VARCHAR(10) COMMENT "상권업종소분류코드",
    small_category_name VARCHAR(50) COMMENT "상권업종소분류명",
    standard_industry_code VARCHAR(10) COMMENT "표준산업분류코드",
    standard_industry_name VARCHAR(255) COMMENT "표준산업분류명",
    si_do_code VARCHAR(10) COMMENT "시도코드",
    si_do_name VARCHAR(50) COMMENT "시도명",
    si_gun_gu_code VARCHAR(10) COMMENT "시군구코드",
    si_gun_gu_name VARCHAR(50) COMMENT "시군구명",
    administrative_dong_code VARCHAR(10) COMMENT "행정동코드",
    administrative_dong_name VARCHAR(50) COMMENT "행정동명",
    legal_dong_code VARCHAR(10) COMMENT "법정동코드",
    legal_dong_name VARCHAR(50) COMMENT "법정동명",
    lot_number_code VARCHAR(25) COMMENT "지번코드",
    land_division_code VARCHAR(10) COMMENT "대지구분코드",
    land_division_name VARCHAR(50) COMMENT "대지구분명",
    lot_main_number INT COMMENT "지번본번",
    lot_sub_number INT COMMENT "지번부번",
    lot_address VARCHAR(255) COMMENT "지번주소",
    road_name_code VARCHAR(15) COMMENT "도로명코드",
    road_name VARCHAR(255) COMMENT "도로명",
    building_main_number INT COMMENT "건물본번지",
    building_sub_number INT COMMENT "건물부번지",
    building_management_number VARCHAR(50) COMMENT "건물관리번호",
    building_name VARCHAR(255) COMMENT "건물명",
    road_name_address VARCHAR(255) COMMENT "도로명주소",
    old_postal_code VARCHAR(10) COMMENT "구우편번호",
    new_postal_code VARCHAR(10) COMMENT "신우편번호",
    dong_info VARCHAR(50) COMMENT "동정보",
    floor_info VARCHAR(10) COMMENT "층정보",
    room_info VARCHAR(10) COMMENT "호정보",
    longitude DOUBLE COMMENT "경도",
    latitude DOUBLE COMMENT "위도"
);
